apiVersion: v1
kind: Secret
metadata:
  name: skillforge-secret
type: Opaque
stringData:
  # Database Configuration
  DATABASE_HOST: localhost
  DATABASE_PORT: '5432'
  DATABASE_USER: user
  DATABASE_PASSWORD: password
  DATABASE_NAME: database

  # JWT Configuration
  JWT_SECRET: secret
  JWT_EXPIRES_IN: 7d

  # Application Configuration
  NODE_ENV: production
  APP_BASE_URL: https://skillforge.example.com

  # S3 Configuration
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: access_key_id
  AWS_SECRET_ACCESS_KEY: secret_access_key
  AWS_S3_BUCKET: skillforge
  AWS_S3_ENDPOINT: endpoint # Leave empty if using aws, otherwise use the endpoint URL

  # AI Provider Configuration
  AI_PROVIDER: gemini # or ollama

  # Gemini Configuration
  GEMINI_API_KEY: api_key
  GEMINI_MODEL: gemini-3.1-flash-lite

  # Ollama Configuration
  OLLAMA_BASE_URL: http://localhost:11434

  # Piston Configuration
  PISTON_BASE_URL: http://localhost:2000